version: '3.9'
services:
  typesense:
    container_name: 'typesense'
    image: typesense/typesense:0.24.0
    restart: unless-stopped
    ports:
      - "8108:8108"
    volumes:
      - /home/lena/bfh/seminar/search-engine-volumes/typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
  meilisearch:
    container_name: 'meilisearch'
    image: "getmeili/meilisearch:v1.1"
    restart: unless-stopped
    ports:
      - "127.0.0.1:7700:7700"
    volumes:
      - /home/lena/bfh/seminar/search-engine-volumes/meilisearch:/meili_data
  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    restart: unless-stopped
    volumes: 
      - /home/lena/bfh/seminar/search-engine-volumes/elasticsearch:/usr/share/elasticsearch/data
    ports: 
      - "9200:9200"
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
